# YAML file to upload new CSV files in the local data/ folder to specified GCS bucket

name: Upload New CSVs to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest  #Github hosted linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_PROJECT_KEY }}

      - name: Confirm Auth Context
        run: |
          gcloud auth list
          gcloud config list

      - name: Upload CSVs to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: data/
          destination: cso-exercise-ingestion-raw/
          parent: false

          