name: Deploy Dataflow Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv lloy_venv
          source lloy_venv/bin/activate
          pip install -r requirements.txt

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_PROJECT_KEY }}

      - name: Deploy pipeline to Dataflow
        run: |
          source lloy_venv/bin/activate
          python pipelines/cso_dataflow_pipeline.py \
            --runner DataflowRunner \
            --project cso-deng-pipeline \
            --region us-central1 \
            --zone=us-central1-a \
            --temp_location gs://cso-exercise-ingestion-raw/temp \
            --staging_location gs://cso-exercise-ingestion-raw/staging \
            --streaming
