name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Terraform Init
        run: terraform init
        working-directory: ./gcs-bucket-terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: ./gcs-bucket-terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
        working-directory: ./gcs-bucket-terraform
