name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # <— Adds a "Run workflow" button

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_PROJECT_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./gcs-bucket-terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./gcs-bucket-terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: ./gcs-bucket-terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
        working-directory: ./gcs-bucket-terraform
